### ISSUE TITLE
allow tile vector shapefiles to be kept in a user-accessible directory

### ISSUE THREAD

**Issue by bhbraswell** [matthewhanson/gips#22]
Currently tile vectors must reside in /etc/gips/datasetname. Many users will find it more convenient to keep these data inside the dataset tree, or some other location that is easily accessible by the user.

**Comment by ircwaves** [comment]
@matthewhanson is this the same issue as #20?

**Comment by matthewhanson** [comment]
Yes, I had expanded #20 to include this requirement as well.

**Comment by bhbraswell** [comment]
To me it looked like #20 is only referring to the DB connection. Though I see you wrote “or anywhere else”. OK.

**Comment by matthewhanson** [comment]
The problem here is that if you install via pip (or even just by setup), but edit your settings file after setup, then the system doesn't know where your repositories are when it is installing the tiles vectors.   Thus, I put them in /etc/gips.   But really they probably belong in the repository like they did before.

This requires some cleaning up of setup, possibly an interactive config utility upon first install, and making sure the whole thing works nicely in a development environment as well as on the system.

16-24 hours

**Comment by bhbraswell** [comment]
I do think the normal way to use GIPS is to have it installed at the system level, rather than in dev mode, but that users will mostly be the people dealing with configuring and adjusting settings.

**Comment by ircwaves** [comment]
again, per new data-driver and settings architecture, this seems fixed.
