### ISSUE TITLE
final0.8.0: extra `.cdl` in path

### ISSUE THREAD

**Issue by ircwaves** [matthewhanson/gips#43]
```
(Pdb) p cls
<class 'gips.data.cdl.cdl.cdlRepository'>
```

Just checking if that `.cdl` is expected, or if I have things installed incorrectly for this `final0.8.0` branch.

**Comment by matthewhanson** [comment]
Yes, as data sources are moved into directories, and the code is in a file also with that name, so:

data/cdl/cdl.py
And in that is cdlRepository.

That being said, since **init**.py imports cdlRepository from cdl in that namespace (essentially one level up), then you can actually import data.cdl.cdlRepository, although the path in the class will show the complete path.

**Comment by ircwaves** [comment]
very good.  just checking that I hadn't barfed the install.
